global:
  # Default is 0: all cores used.
  # If max_used_cores(n) < 0, what it means is total cores - n
  max_used_cores: 1
  # Crawing interval(min): default is 5min.
  interval: 5

scraper:
  visit_domains:
    - https://news.naver.com
    - https://news.daum.net
  # allowed_domains:
  #   - https://news.naver.com
  #   - https://news.daum.net
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
  async: true
  max_depth_to_visit: 1

emitter:
  elasticsearch:
    hosts:
      - http://elasticsearch:9200
    username: elastic
    password: changeme
