version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    #expose:
    #  - "9200"
    #restart: always
    privileged: true

  kibana:
    container_name: kibana
    image: kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    environment:
      - TZ=Asia/Seoul
    #restart: always
    privileged: true

volumes:
  esdata:
    driver: local
